### ISSUE TITLE
Make client secret comparison use a timing safe HMAC function

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/oauth2-token-endpoint-handler#4]
In `_authenticateClient()`, the `if(clientSecret !== storedClientSecret) {` line.

From @dlongley:

It can't be simple string comparison because that will leak timing information that will enable an attacker to figure out client secrets. Instead we need to use a constant-time API call to do the comparison, i.e., no matter what value is passed in, the comparison will take the same amount of time (or, alternatively, it will appear random to an attacker). We don't want attackers gaining information by failed comparisons.

In this case, we really shouldn't be storing the client secret at all if we can avoid that. We should instead HMAC it. Then we can HMAC the value given to us for comparison and use [crypto.timingSafeEqual](https://nodejs.org/dist/latest-v6.x/docs/api/crypto.html#crypto_crypto_timingsafeequal_a_b) to compare the resulting buffers containing the signature values/digests.

**Comment by dlongley** [comment]
Marking this as critical/Priority 1 ... needs to be fixed or this module is not secure. We may want to make the client secret comparison a plugin (callback function) here so that systems can customize for their needs. And then it would be on those applications to implement properly and this issue could be closed (and a similar one opened in any applications that are trying to use this).

**Comment by dmitrizagidulin** [comment]
This has actually been implemented in a previous release (`authenticateClient` is one of the callbacks passed in to the handler).
Closing.
